name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Copy root index
      - name: Copy root index
        run: |
          mkdir -p dist
          cp index.html dist/

      # Build egg-prices
      - name: Build egg-prices
        run: |
          cd egg-prices
          npm ci
          npm run build
          mkdir -p ../dist/egg-prices
          cp -r dist/* ../dist/egg-prices/

      # Deploy to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
